### ISSUE TITLE
Add Drag and Drop Functionality to the Smart Compressor

### ISSUE THREAD

**Issue by yashshree7** [Gitesh08/smart-compressor#1]
Hello,
I have a suggestion to enhance the usability of the Smart Compressor project by adding a drag and drop feature for file uploads. Currently, users must manually select files for compression, which might be less intuitive for some users. A drag-and-drop option would:
Improve the user experience by making file selection faster and easier. 
If needed, I can contribute to implementing this feature.
Thank you for considering my suggestion!

**Comment by Gitesh08** [comment]
> Hello,
> 
> I have a suggestion to enhance the usability of the Smart Compressor project by adding a drag and drop feature for file uploads. Currently, users must manually select files for compression, which might be less intuitive for some users. A drag-and-drop option would:
> 
> Improve the user experience by making file selection faster and easier. 
> 
> If needed, I can contribute to implementing this feature.
> 
> Thank you for considering my suggestion!

@yashshree7 This is great idea! Can you propose solution and couple of screenshots for same

**Comment by yashshree7** [comment]
Attached screenshots for the same.

![Screenshot (4)](https://github.com/user-attachments/assets/ed44a57e-617d-44f6-881b-4dd9e6c61501)
![Screenshot (5)](https://github.com/user-attachments/assets/dc4dd108-7454-4851-985a-2fbf2a18d420)
![Screenshot (6)](https://github.com/user-attachments/assets/b18ad2ef-ecd7-4aa5-a094-afc713d477f4)

**Comment by yashshree7** [comment]
Attaching Screenshots for the same.

![Screenshot (7)](https://github.com/user-attachments/assets/70098cca-d754-4b16-b606-dade96c1029b)
![Screenshot (8)](https://github.com/user-attachments/assets/3a7000ee-5915-4b3e-8ced-908f0da9a8a8)

**Comment by Gitesh08** [comment]
> Attaching Screenshots for the same.
> 
> ![Screenshot (7)](https://private-user-images.githubusercontent.com/132804726/389579639-70098cca-d754-4b16-b606-dade96c1029b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDY3NjAsIm5iZiI6MTczMjU0NjQ2MCwicGF0aCI6Ii8xMzI4MDQ3MjYvMzg5NTc5NjM5LTcwMDk4Y2NhLWQ3NTQtNGIxNi1iNjA2LWRhZGU5NmMxMDI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxNDU0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmY4NjY4Y2UxNmMwNjE4ZjhlOWQxZjJhMGJjZjNiMWE4YjdmZTdiNjI3M2ZiMDJlZDdmN2Y1YzY3MzU1MDI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N6LVKVPFj-Ye54Lctll12sIiMcBFrD9qb72OzxQD0yc) ![Screenshot (8)](https://private-user-images.githubusercontent.com/132804726/389579667-3a7000ee-5915-4b3e-8ced-908f0da9a8a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDY3NjAsIm5iZiI6MTczMjU0NjQ2MCwicGF0aCI6Ii8xMzI4MDQ3MjYvMzg5NTc5NjY3LTNhNzAwMGVlLTU5MTUtNGIzZS04Y2VkLTkwOGYwZGE5YThhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxNDU0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWU1MmFjM2UwMThhNGEzMzI5NTY0MTFlZWE0ODgxYmJhNzFhNDNjY2VkMDkxYWJhYTdmNmIwY2JlNWJlYTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nQblH5nB9H5Sy_A-IfjnKKtxSPh93_DM2ynkoJjn7gE)

Looks great! I have created new branch please go ahead with PR. Thank you

**Comment by yashshree7** [comment]
Sure, Thank you.
